"""empty message

Revision ID: 19105f3112e4
Revises: 4eda30af3d08
Create Date: 2019-04-24 21:19:45.940778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19105f3112e4'
down_revision = '4eda30af3d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('is_posted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'is_posted')
    # ### end Alembic commands ###
