"""empty message

Revision ID: 2ae45474ecec
Revises: dd22071d9a3e
Create Date: 2019-04-16 15:53:05.104188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae45474ecec'
down_revision = 'dd22071d9a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'created')
    # ### end Alembic commands ###
