"""empty message

Revision ID: a1ab4733a589
Revises: 19105f3112e4
Create Date: 2019-04-24 21:20:16.011477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ab4733a589'
down_revision = '19105f3112e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('gallery_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'gallery_id')
    # ### end Alembic commands ###
