export const GET_GALLERY = "GET_GALLERY";
export const GET_GALLERY_SUCCESS = "GET_GALLERY_SUCCESS";
export const GET_GALLERY_FAIL = "GET_GALLERY_FAIL";

export const GET_MEDIA = "GET_MEDIA";

export const POST_EMAIL = "POST_EMAIL";
export const POST_EMAIL_SUCCESS = "POST_EMAIL_SUCCESS";
export const POST_EMAIL_FAIL = "POST_EMAIL_FAIL";
